# Generated by Django 4.1.3 on 2023-02-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odam', models.CharField(max_length=31)),
                ('nomi', models.CharField(max_length=31)),
                ('rasm1', models.CharField(max_length=255)),
                ('rasm2', models.CharField(max_length=255)),
                ('read', models.IntegerField(default=2)),
                ('haqida', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, to='core.toppost')),
            ],
        ),
    ]
